### ISSUE TITLE
.gemspec file incompatible with ruby environment managers

### ISSUE THREAD

**Issue by gl-yziquel** [prawnpdf/ttfunk#103]
The `gem build ttfunk.gemspec` command fails because of the following line:

https://github.com/prawnpdf/ttfunk/blob/master/ttfunk.gemspec#L14

It looks up the signing key in a location that is incompatible with an system based on ruby environment managers such as rvm or rbenv.

It triggers the following error:

```console
ERROR:  While executing gem ... (Errno::ENOENT)
    No such file or directory @ rb_sysopen - /home/mini-me/.gem/gem-private_key.pem
```

Maybe it would make sense to gate this feature behind the invocation of some option or flag.

**Comment by gl-yziquel** [comment]
Oh. It's fixed in the version I pulled. Sorry. Closing.

**Comment by pointlessone** [comment]
Ah, good. Because for a minute I was really puzzled looking at the code in the repo.
