### ISSUE TITLE
warning: instance variable @offset not initialized

### ISSUE THREAD

**Issue by jakoch** [prawnpdf/ttfunk#31]
`/home/travis/.rvm/gems/ruby-2.3.1/gems/ttfunk-1.4.0/lib/ttfunk/table.rb:25: warning: instance variable @offset not initialized`

**Comment by pointlessone** [comment]
Hello Jens,

Thank you for reporting the warning. Would you be willing to submit a fix as well?

**Comment by jakoch** [comment]
Hey :) sorry, i'm not a ruby guy.

**Comment by pointlessone** [comment]
No problem. Thank you for your contribution.

Just in case you're worried about the warning. It's not a big deal. Ruby give a lot of hints how to improve code to avoid potential problems. In this case it's OK. We'll get to fixing all the warnings. Eventually.

**Comment by hidakatsuya** [comment]
This warning has been fixed by #41

**Comment by pointlessone** [comment]
@hidakatsuya Tank you.
