### ISSUE TITLE
Unable to use kerning

### ISSUE THREAD

**Issue by daniellAlgar** [prawnpdf/ttfunk#34]
Hi all!

I'm facing an issue where the kerning isn't read properly from the font. 

```
file_name = ARGV.first || File.join(__dir__, './my_font.ttf')
file = TTFunk::File.open(file_name)
puts "kerning? : #{file.kerning.exists?}"
```

result in `kerning? : false`

The font does contain kerning and I've verified it by installing it in the MacOS Font Book and used the font in TextEdit. 

Any thoughts or similar experiences? Or even better, any solution?

**Comment by ramhoj** [comment]
+1

**Comment by mojavelinux** [comment]
This is due to the fact that ttfunk only recognizes kerning in a font that either has an old-style kern table or is in the Apple TTF format. These are both options when you can enable when you save the font with FontForge.

See the second screenshot on https://fontforge.github.io/en-US/documentation/interface/generate/.

If you're using a FontForge script, you'd set the following flags:

```
genflags = 0x90 + 0x800 + 0x04
```

which I pass into the Generate command as follows:

```
Generate(export_file, "", genflags)
```

**Comment by mojavelinux** [comment]
I think that saving in the Apple format is just another way of enabling the old-style kern table.

**Comment by mojavelinux** [comment]
Btw, those flags are:

* 0x90 - neither OpenType or Apple
* 0x800 - generate old-style 'kern' table
* 0x04 - exclude PS glyph names

It isn't necessary to trim the font down like that. It's just what I use.

**Comment by daniellAlgar** [comment]
@mojavelinux Thanks a million! That was indeed the issue. 

As a side note: FontForge warns about 

```
Ignoring 'LTSH' linear threshold table
Ignoring 'VDMX' vertical device metrics table
Ignoring 'hdmx' horizontal device metrics table
```

Is that serious in any way?

**Comment by mojavelinux** [comment]
You're welcome!

When I first used FontForge, those warnings really worried me too.
Experience has taught me that FontForge is just very detailed about
compliance issues. I've yet to find a case where a warning translated into
a messed up glyph. And 90% of fonts (hand waving) are noncompliant in some
way, even really good ones.

**Comment by daniellAlgar** [comment]
Sounds good enough :). 

Thank you so much again! I'm closing this issue.
