### ISSUE TITLE
Subset object fails to encode if table data is empty

### ISSUE THREAD

**Issue by mojavelinux** [prawnpdf/ttfunk#39]
If the data in one of the tables is empty, the Subset object fails to encode. This bug was introduced when the checksum method was rewritten prior to 1.5.0.

See https://github.com/prawnpdf/ttfunk/commit/129d423272378d00c8b916e8a3c337f062274b27#diff-45b279937f00663adf564be8dead1e57L126

The method no longer accounts for a zero-length string. When the string is empty, the method returns false instead of 0.

**Comment by mojavelinux** [comment]
This bug causes ttfunk to crash when working with many fonts.

**Comment by pointlessone** [comment]
This is fixed in 1.5.1.
