### ISSUE TITLE
NoMethodError: undefined method `key?' when encoding a subset

### ISSUE THREAD

**Issue by camertron** [prawnpdf/ttfunk#45]
Hey guys,

First of all, thanks for all the work you do on Prawn and TTFunk! The ruby community really appreciates it :)

I'm trying to use TTFunk to subset the Noto font, but getting an error with the following snippet (adapted from looking at the tests):

```ruby
font = TTFunk::File.open('path/to/NotoSansCJKjp-Regular.otf')
subset = TTFunk::Subset.for(font, :unicode)
subset.use(0x304b)  # Katakana letter "ka"
subset.encode
```

I get the following error:

```
NoMethodError: undefined method `key?' for nil:NilClass
  from /Users/cameron/workspace/ttfunk/lib/ttfunk/table/glyf.rb:30:in `for'
  from /Users/cameron/workspace/ttfunk/lib/ttfunk/subset/base.rb:158:in `block in collect_glyphs'
  from /Users/cameron/workspace/ttfunk/lib/ttfunk/subset/base.rb:157:in `each'
  from /Users/cameron/workspace/ttfunk/lib/ttfunk/subset/base.rb:157:in `each_with_object'
  from /Users/cameron/workspace/ttfunk/lib/ttfunk/subset/base.rb:157:in `collect_glyphs'
  from /Users/cameron/workspace/ttfunk/lib/ttfunk/subset/base.rb:32:in `encode'
```

It looks like the [`@cache` variable is `nil`](https://github.com/prawnpdf/ttfunk/blob/086b3126b13d207abf992279bef9b7699af8ae32/lib/ttfunk/table/glyf.rb#L30).

Any idea why that would be? I would be happy to track down the issue and submit a pull request, but I have no idea where to start. Thanks!

Oh, and here's the font in question:

[NotoSansCJKjp-Regular.otf.zip](https://github.com/prawnpdf/ttfunk/files/1400868/NotoSansCJKjp-Regular.otf.zip)

**Comment by pointlessone** [comment]
The `glyf` table might not have been parsed. Cache is initialized during the parsing. The reason might be that TTfunk doesn't officially support OTF.

**Comment by pointlessone** [comment]
I will close this issue now. Feel free to reopen if you feel like your issue is not resolved.

**Comment by camertron** [comment]
Ah ok that makes sense. Thanks @pointlessone :)
