### ISSUE TITLE
Embedded font issue

### ISSUE THREAD

**Issue by meap** [prawnpdf/ttfunk#73]
I've updated ttfunk from `1.5.1` to `1.6.1` and encountered an issue with embedded fonts. I am not sure if it is related to #72.

<img width="532" alt="Screenshot 2020-01-10 at 10 07 34" src="https://user-images.githubusercontent.com/36914/72140618-6cfcc200-3391-11ea-991e-51f2491b7185.png">

You can find attached the [PDF](https://github.com/prawnpdf/ttfunk/files/4044792/pages.pdf).

**Comment by edward-ellis** [comment]
According to the bug report linked below in mid-2019 Adobe Reader became more picky about ignoring some embedded font errors. If the PDF file is viewed using the Chrome embedded PDF viewer the file displays just fine. However, using my version of Adobe Reader (2019.021.20061) the file contains a flawed embedded font. The bug report says Adobe Pro DC detects and reports the problem, but I currently only have access to Adobe Pro 2017, which doesn't detect any errors.

https://community.adobe.com/t5/acrobat/quot-cannot-extract-the-embedded-font-quot-some-characters-may-not-display-or-print-correctly/td-p/10090976

**Comment by sos4nt** [comment]
I can confirm this. PDFs with embedded fonts can't be opened with the current version of Acrobat Reader DC. Other PDF viewers work fine. We've reverted to 1.5.1 for the meantime.

Please prioritize this issue, Acrobat Reader support is crucial when working with PDF files.

**Comment by cmbaldwin** [comment]
Also can confirm this. Thanks for looking into this.
I posted about the issue (and discovered this discussion) here: https://stackoverflow.com/questions/59743505/embedded-font-error-for-rails-prawn-document

**Comment by whitmer** [comment]
Same, spent a few hours troubleshooting a multi-font file that wouldn't print before I found this. Reverting to 1.5.1 fixed the issue.

**Comment by timokleemann** [comment]
Just ran into the same issue. Reverting to 1.5.1 fixed it for me too.

**Comment by flavio-b** [comment]
Also run into the same issue. The PDF opens fine with Chrome's PDF viewer, Safari or Preview. Adobe Readers shows an error message "Cannot extract font...". 
Reverting to 1.5.1 also fixed the issue.

**Comment by mmccarthy15** [comment]
For what it's worth, older versions of Adobe Acrobat are giving this same error.  I have a user using Acrobat XI - 11.0.23, and it's the same error.

**Comment by pointlessone** [comment]
This issue should be fixed in TTFunk 1.6.2. Please upgrade and report any issues you have. Thank you for patience.

**Comment by timokleemann** [comment]
I can confirm that upgrading to version 1.6.2 fixes it for me. Thanks!

**Comment by JalisoCSP** [comment]
> I can confirm that upgrading to version 1.6.2 fixes it for me. Thanks!

I found this through this StackOverflow: https://stackoverflow.com/a/59745102/3767922

We have this problem on ttfunk 1.6.2.1 (and prawn 2.2.2)
