### ISSUE TITLE
Upgrading from 1.5.1 to 1.6.2 adds $stdout to tests and generates .ttf files in project dir

### ISSUE THREAD

**Issue by jeffblake** [prawnpdf/ttfunk#77]
Screens attached. Guessing someone forgot to take out some debugging code?

<img width="347" alt="Screen Shot 2020-02-14 at 9 37 38 AM" src="https://user-images.githubusercontent.com/620564/74554190-c6ff2300-4f0d-11ea-8906-2f6bd7861df7.png">
<img width="1293" alt="Screen Shot 2020-02-14 at 9 37 22 AM" src="https://user-images.githubusercontent.com/620564/74554195-c9617d00-4f0d-11ea-8017-9d7e53420dc0.png">

**Comment by pointlessone** [comment]
Sorry for the inconvenience. I forgot to stash my local changes before I built the gem. 1.6.2.1 fixes this.
