### ISSUE TITLE
Ruby 3 support missing

### ISSUE THREAD

**Issue by johannesluedke** [prawnpdf/ttfunk#89]
Ruby 3.0.0 was released https://www.ruby-lang.org/en/news/2020/12/25/ruby-3-0-0-released/, but the latest release 1.6.2.1 does not work with it: Bundler shows this error `ttfunk-1.6.2.1 requires ruby version ~> 2.4, which is incompatible with
the current version, ruby 3.0.0p0`

It's apparently already prepared on master with 7db840050c13a755e6b6fd2f2dc4b0ae5edf2998 - can a new release be made of that?  😇

**Comment by pointlessone** [comment]
The latest release of TTFunk supports Ruby 3.

**Comment by johannesluedke** [comment]
thanks 😇 👍

**Comment by PeterWooster** [comment]
What version do I need to specify for  gem prawn to get the latest version of TTFunk?   It still brings in version 1.6.2.1 which doesn't work with ruby 3.
