### ISSUE TITLE
Please release the new version

### ISSUE THREAD

**Issue by yoshoku** [prawnpdf/ttfunk#91]
I would appreciate it if you could consider for releasing the new version.
It is been over a year since the latest version was released.
In the meantime, two pull requests that provide significant performance improvements have been merged.

- [Improve Performance of TTFunk::Table::OS2#group_original_code_points_by_bit #83](https://github.com/prawnpdf/ttfunk/pull/83)
- [Reduce memory allocations and enhance performance #90](https://github.com/prawnpdf/ttfunk/pull/90)

Releasing these changes is valuable to users and gems that depend on ttfunk.
Thank you for your consideration.

**Comment by yoshoku** [comment]
Thank you for consideration.

**Comment by gettalong** [comment]
@yoshoku There has been quite a flurry of activity in January/February but the Russian war against Ukraine brought it to a halt. So please have so patience for the time being - thanks!

**Comment by yoshoku** [comment]
Thank you for your courteous reply. I understood the situation. I pray that peaceful days will return as soon as possible.
