### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by mariuszpala** [prawnpdf/ttfunk#96]
Hi, 

I was about to use asciidoctorj-pdf for my project (commercial), but I noticed that although that project is under Apache 2.0 licence, it contains ttfunk gem which seems to be under GPL. That means we cannot really use it without sharing our source code. 
Is my understanding correct? In general asciidoctorj-pdf uses jruby which includs prawn which includes ttfunk. Just ttfunk in the whole dependency tree is under GPL and not Ruby license. 
Can you please clarify whether this prevents us using the parent library in a commercial project?

For reference: https://github.com/asciidoctor/asciidoctorj-pdf/issues/69

**Comment by pointlessone** [comment]
1. TTFunk is a multi-license gem (as Prawn, pdf-core, and prawn-table are, too). You can chose which license to use. The licenses are GPL2, GPL3, or Prawn license (based on Ruby license). Here's a [copy](https://github.com/prawnpdf/ttfunk/blob/master/LICENSE).
2. Even under GPL you don't need to share you code if you're just using asciidoctor-pdf as a stand-alone tool. For example, your app/lib code doesn't need to be published if you're using asciidoctor for documentation. Only the extensions to asciidoctor-pdf might need to be published if you have any.

**Comment by pointlessone** [comment]
I can't say anything for asciidoctor but you can distribute prawn gems under Prawn license without having to release your source code. Specifically, according to paragraph 3 it should be enough to link to Prawn somewhere in your docs to satisfy the license.

To clarify, you can chose one of the three licenses. You don't have to satisfy all three at the same time (I'm not sure that's even possible). From what I gathered you want to chose the Prawn license.

**Comment by mariuszpala** [comment]
Thank you for the clarification
